name: Assignment tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '0.6.8'

      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.12.16'

      - name: Setup cljstyle
        uses: just-sultanov/setup-cljstyle@v1
        with:
          version: '0.15.0'

      - name: Run linters
        run: bb lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup openjdk
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          bb: 'latest'

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}

      - name: Run unit tests
        run: bb test
